[project]
name = "vcl"
version = "0.1.0"
description = "Virtual Climate Lab: an interactive table to discuss the future of your environment."
readme = "README.rst"
requires-python = ">=3.10"
license = "GPL-3.0-only"
authors = [
    { name = "Guus van Hemert", email = "guus.vanhemert@deltares.nl" }
]
keywords = ["vcl"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8"
]
dependencies = [
    "Click>=7.0",
    "pyzmq",
    "xarray",
    "rioxarray",
    "scipy",
    "numpy>=1.24.4",
    "netCDF4>=1.6.5",
    "cmocean",
    "opencv-python",
    "geopandas>=0.14",
    "rasterio",
    "matplotlib>=3.4,<3.8",
    "shapely",
    "pandas",
    "mido",
    "python-rtmidi",
    "pygame>=2.6.1",
    "pygetwindow>=0.0.9",
    "screeninfo>=0.7",
    "seaborn>=0.11.2",
    "geocube>=0.0.16",
    "owslib>=0.31.0",
    "pyqt5>=5.15.6",
    "tqdm>=4.64.1",
    "mediapipe>=0.10.21",
    "setuptools>=59.6.0",
]

[project.optional-dependencies]
test = ["pytest>=3"]

[project.urls]
Homepage = "https://github.com/openearth/vcl"

[project.scripts]
vcl = "vcl.cli:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["vcl", "vcl.*"]
